export const dataList = [
  {
    id: 1,
    title: "UAE",
    bgImage: "/assets/works/uaeBg.webp",
    avatarImage: "/assets/works/uaeGuy.png",
    image: "/assets/works/uae.png",
    projectLink: "/works/uae",
    color: "#5d5c5c",
    mobileImage: "/assets/works/uaeMob.png",
    projects: [
      {
        id: 1,
        title: "Title 1",
        description: "Description 1",
        image: "/assets/works/education/workEduImg1.jpg",
      },
    ],
  },
  {
    id: 2,
    title: "india",
    bgImage: "/assets/works/indiaBg.webp",
    avatarImage: "/assets/works/indiaGuy.png",
    image: "/assets/works/india.png",
    projectLink: "/works/india",
    color: "#aeefc5",
    mobileImage: "/assets/works/indiaMob.png",
    projects: [
      {
        id: 1,
        title: "Title 1",
        description: "Description 1",
        image: "/assets/works/education/workEduImg1.jpg",
      },
    ],
  },
  {
    id: 3,
    title: "Education",
    bgImage: "/assets/works/eduBg.webp",
    avatarImage: "/assets/works/eduGuy.png",
    image: "/assets/works/edu.png",
    projectLink: "/works/education",
    color: "#eb6425",
    mobileImage: "/assets/works/eduMob.png",
    projects: [
      {
        id: 1,
        title: "Title 1",
        description: "Description 1",
        image: "/assets/works/education/workEduImg1.jpg",
      },
      {
        id: 2,
        title: "Title 2",
        description: "Description 2",
        image: "/assets/works/education/workEduImg2.jpg",
      },
      {
        id: 3,
        title: "Title 3",
        description: "Description 3",
        image: "/assets/works/education/workEduImg3.jpg",
      },
      {
        id: 4,
        title: "Title 4",
        description: "Description 4",
        image: "/assets/works/education/workEduImg4.jpg",
      },
      {
        id: 5,
        title: "Title 5",
        description: "Description 5",
        image: "/assets/works/education/workEduImg5.jpg",
      },
    ],
  },
  {
    id: 4,
    title: "Art",
    bgImage: "/assets/works/artBg.webp",
    avatarImage: "/assets/works/artGuy.png",
    image: "/assets/works/art.png",
    projectLink: "/works/art",
    color: "#812333",
    mobileImage: "/assets/works/artMob.png",
    projects: [
      {
        id: 1,
        title: "Title 1",
        description: "Description 1",
        image: "/assets/works/education/workEduImg1.jpg",
      },
    ],
  },
];
